'''
Author: Orange (Generated by Antigravity)
Date: 2026-03-03
Description: 单点目标验证脚本 - 验证修复后的雷达仿真管线的距离和角度精度
'''

import numpy as np
import sys
import os

# 直接导入具体模块，避免 utils/__init__.py 触发 pyrealsense2 依赖
import importlib.util

def _load_module(name, filepath):
    spec = importlib.util.spec_from_file_location(name, filepath)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod

_base = os.path.join(os.path.dirname(os.path.abspath(__file__)), "utils")
_cfg_mod = _load_module("radar_config", os.path.join(_base, "radar_config.py"))

# radar_dsp.py 使用 from .radar_config import RadarConfig 的相对导入
# 需要先创建一个假的 utils 包并注册 radar_config 子模块
import types
_pkg = types.ModuleType("utils")
_pkg.__path__ = [_base]
sys.modules["utils"] = _pkg
sys.modules["utils.radar_config"] = _cfg_mod
_dsp_mod = _load_module("utils.radar_dsp", os.path.join(_base, "radar_dsp.py"))

RadarConfig = _cfg_mod.RadarConfig
simulate_adc = _dsp_mod.simulate_adc
process_radar_data = _dsp_mod.process_radar_data
extract_point_cloud = _dsp_mod.extract_point_cloud

def test_single_target(x_gt, y_gt, z_gt, vx=0.0, vy=0.0, vz=0.0, label=""):
    """放置一个已知位置的单点目标，验证雷达输出是否正确恢复"""
    config = RadarConfig()
    
    pc = np.array([[x_gt, y_gt, z_gt]])
    vel = np.array([[vx, vy, vz]])
    rcs = np.array([1.0])  # 强反射
    
    # 仿真 ADC
    adc_cube = simulate_adc(pc, vel, rcs, config)
    
    # DSP 处理
    rdm, az_fft, el_fft, range_axis, doppler_axis, theta_axis, phi_axis = process_radar_data(adc_cube, config)
    
    # 提取点云
    radar_pc = extract_point_cloud(az_fft, el_fft, range_axis, doppler_axis, theta_axis, phi_axis, rdm)
    
    # 计算真实距离
    r_gt = np.sqrt(x_gt**2 + y_gt**2 + z_gt**2)
    
    print(f"\n{'='*60}")
    print(f"测试: {label}")
    print(f"  真实位置:  x={x_gt:.2f}, y={y_gt:.2f}, z={z_gt:.2f}  (R={r_gt:.2f} m)")
    print(f"  检出点数:  {len(radar_pc)}")
    
    if len(radar_pc) > 0:
        # 找最强反射点
        best_idx = np.argmax(radar_pc[:, 4])
        x_est, y_est, z_est, v_est = radar_pc[best_idx, :4]
        r_est = np.sqrt(x_est**2 + y_est**2 + z_est**2)
        
        dx = x_est - x_gt
        dy = y_est - y_gt
        dz = z_est - z_gt
        err_3d = np.sqrt(dx**2 + dy**2 + dz**2)
        
        print(f"  估计位置:  x={x_est:.3f}, y={y_est:.3f}, z={z_est:.3f}  (R={r_est:.3f} m)")
        print(f"  位置误差:  Δx={dx:.3f}, Δy={dy:.3f}, Δz={dz:.3f}")
        print(f"  3D 误差:   {err_3d:.3f} m")
        print(f"  距离误差:  {abs(r_est - r_gt):.3f} m  (分辨率 ≈ {config.c / (2 * config.B):.3f} m)")
        
        passed = err_3d < 0.5  # 0.5m 容差
        print(f"  结果:      {'[PASS]' if passed else '[FAIL]'}")
        return passed
    else:
        print(f"  结果:      [FAIL] (wei jian chu ren he mu biao)")
        return False

def main():
    print("=" * 60)
    print("雷达仿真管线单点目标验证")
    print("=" * 60)
    
    results = []
    
    # 测试 1: 正前方目标
    results.append(test_single_target(0, 3, 0, label="正前方 3m"))
    
    # 测试 2: 正前方不同距离
    results.append(test_single_target(0, 5, 0, label="正前方 5m"))
    
    # 测试 3: 带方位角偏移
    results.append(test_single_target(1, 3, 0, label="偏右 1m, 深度 3m (θ≈18°)"))
    
    # 测试 4: 带高度偏移
    results.append(test_single_target(0, 3, 0.5, label="正前方 3m, 高度 0.5m"))
    
    # 测试 5: 带速度
    results.append(test_single_target(0, 3, 0, vy=1.0, label="正前方 3m, 径向速度 1m/s"))
    
    print(f"\n{'='*60}")
    print(f"总结: {sum(results)}/{len(results)} 通过")
    print("=" * 60)

if __name__ == "__main__":
    main()
